name: tiemout

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true           # Cancel older runs on same branch

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10              # Job timeout
    steps:
      - name: ⏱️ Step with Timeout
        timeout-minutes: 1  # Step timeout
        continue-on-error: true
        run: |
          echo "This step must complete in 1 minutes"
          sleep 90
          echo "Completed within time!"

      - name: verify fail
        run: echo "test successfull"


  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 16, 18]
    steps:
    # Steps that use the matrix variables
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and run tests
        run: npm ci && npm test
