name: Workflow01

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello from Himanshu in the GH-200 Session"

      - name: Copy Repo
        uses: actions/checkout@v6

      - name: List Files
        run: ls -la

      - name: Generate ASCII Art
        run: |
          sh $HOME/scripts/greet.sh
